name: EventListeners
version: '1.0'
main: me.jackway.eventlisteners.EventListeners
api-version: 1.19
commands:
  die:
    description: An easy way to kys
    usage: /<command>
  god:
    description: Become invincible
    usage: /<command>
    aliases:
      - pro
      - beastmode
  printMessageFromConfig:
    description: config test
  menu:
    description: Open the bending menu
    usage: /<command>
    aliases:
      - bending
      - skills